################################################################################
#
#
# Copyright(c) 1999 - 2009 Intel Corporation. All rights reserved.
#
# Makefile for building ixgbe sv driver
#
################################################################################
#ARCH := $(shell uname -m | sed 's/i.86/i386/')

REDHAT_DISTRIB:=$(shell grep -lr "Santiago" /etc/*-release 2>/dev/null)

ccflags-y := -I$(src)/../sv_shared
ccflags-y += -I$(src)/../api/inc
ccflags-y += -I$(src)/../ixgbe
ccflags-y += -I$(src)/../ixgbe/shared

ccflags-y += -O2 # optimize for performance
ccflags-y += -DIXGBE
ccflags-y += -DFCOE_SUPPORTED
ccflags-y += -DDISABLE_FORCE_GEN3
ccflags-y += -DSYSLOG_PRINTS
ccflags-y += -DDMA_SW_FLUSH
ccflags-y += -DSV_RSC
ccflags-y += -DHW_SV
ccflags-y += -DMAGNOLIA_PARK_HW
ccflags-y += -DBROADWELL_HW
ccflags-y += -DDENVERTON_HW

#ccflags-y += -DSINGLE_PF
#ccflags-y += -DRX_BUFFER_ALLOC_CHECK_LOW_LEVEL_MEM
#ccflags-y += -DRX_HANDLER_TIME
#ccflags-y += -Winline
#ccflags-y += -DCHECKER_DISABLED
ccflags-y += -DDESC_INVERT
ccflags-y += -DDRIVER_ONLY
#ccflags-y += -DOLD_TX_HANDLER
ccflags-y += -DOVERWRITE_RS_BIT

######## debug flags ####################
#ccflags-y += -DTX_DBG
#ccflags-y += -DPRINT_CSR_WRITE
#ccflags-y += -DPRINT_PACKET_UID
#ccflags-y += -DDBG
#ccflags-y += -DPRINT_TX_BUFFER

######## workaround flags ####################
#ccflags-y += -DBYPASS_ADVANCED_HANG_ANALYSYS
#ccflags-y += -DBYPASS_PHY_IDENTIFICATION
#ccflags-y += -DIXGBE_BDX_IGNORE_SFP_NOT_PRESENT

ccflags-y += -Wno-unused-variable

ifneq ($(REDHAT_DISTRIB),)
        ccflags-y += -DNO_CUSTOM_KMEM_CACHE
endif



# If we compile for SVOS, change target module name (suffix it with "sv")
ifeq ($(SVOS),1)
	ccflags-y += -DSVOS
	target_obj := ixgbesv.o
	objects := ixgbesv-y

else
	target_obj = ixgbe.o
	objects = ixgbe-y
endif

obj-m += $(target_obj)


$(objects) :=   shared/ixgbe_common.o\
                shared/ixgbe_phy.o\
                shared/ixgbe_api.o\
                shared/ixgbe_82598.o \
                shared/ixgbe_82599.o \
                shared/ixgbe_x540.o \
                shared/ixgbe_x550.o \
                shared/ixgbe_mbx.o \
                shared/kcompat.o \
                ixgbe_main.o\
                ixgbe_rx_ring.o \
                ixgbe_tx_ring.o \
                ixgbe_mem.o \
                ixgbe_intr.o\
                ixgbe_fcoe.o\
                ixgbe_diag.o\
                ixgbe_iov.o\
		sv_shared/sv_main.o\
                sv_shared/sv_ctrl.o\
                sv_shared/sv_ctrl_cmds.o\
                sv_shared/sv_mem.o\
                sv_shared/sv_rx_ring.o\
                sv_shared/sv_rx_isr.o\
                sv_shared/sv_rx_ring_adv.o\
                sv_shared/sv_tx_ring.o\
                sv_shared/sv_diag.o\
                sv_shared/sv_queue.o\
                sv_shared/sv_log.o\
                sv_shared/sv_error.o\
                sv_shared/sv_packetcollector.o\
                sv_shared/sv_rx_packet.o\
                sv_shared/sv_intr.o\
                sv_shared/sv_exp_table.o\
                sv_shared/sv_events.o\
                sv_shared/sv_iov.o\
                sv_shared/sv_fcoe.o\
                sv_shared/sv_config.o\
                sv_shared/sv_thx.o\
                sv_shared/sv_cc.o\
                sv_shared/sv_cc_desc_ops.o
