################################################################################
#
# 
# Copyright(c) 1999 - 2010 Intel Corporation. All rights reserved.
# 
# Makefile for building i40e sv driver
#
################################################################################

RDMA	?= 0

REDHAT_DISTRIB:=$(shell grep -lr "Santiago" /etc/*-release 2>/dev/null)

ccflags-y += -I$(src)/../sv_shared/
ccflags-y += -I$(src)/../api/inc/
ccflags-y += -I$(src)/../api/iwarp/inc/
ccflags-y += -I$(src)/../i40e/lan/
ccflags-y += -I$(src)/../i40e/iwarp/
ccflags-y += -I$(src)/../i40e/shared/
ccflags-y += -I$(src)/../iw_shared/

ccflags-y += -O2     # optimize for performance
ccflags-y += -DI40E
ccflags-y += -DFCOE_SUPPORTED
ccflags-y += -DEXP_TABLE_NO_GAP
# iwarp is current by default disabled
# comment mext line to enable iwarp
#ifeq ($(RDMA),0)
#	ccflags-y += -DDISABLE_IWARP
#else
#ccflags-y += -DSKIP_PFR
#endif\

ccflags-y += -DCHECK_PARAMS
ccflags-y += -DIW_DO_NOT_LOAD_FW
#ccflags-y += -DSINGLE_PF
#ccflags-y += -DMEMDEBUG
#ccflags-y += -DIWARP_PAGED_SD
ccflags-y += -DUDA_ENABLED

ccflags-y += -DRDMA_VIRTCHNL
ccflags-y += -DI40IW_PUDA
ccflags-y += -DMKI_ROCE
ccflags-y += -DSV_DRIVER
#ccflags-y += -DSRQ_SUPPORT
#ccflags-y += -DIWARP_LINUX



#ccflags-y += -DSINGLE_THREADED_ACCESS
#ccflags-y += -DFIX_MAX_PAYLOAD
#ccflags-y += -DI40E_AQ_PRINT_BUFFER
#ccflags-y += -DIWARP_LOW_MEMORY
#ccflags-y += -DFVL_MINIMAL_MSIX_VECTORS
#ccflags-y += -DDISABLE_FORCE_GEN3
#ccflags-y += -DFLASHLESS_MODE  
#ccflags-y += -DDISABLE_REG_READ_WRITE
#ccflags-y += -DFVL_RESUME_TSCD
#ccflags-y += -DFVL_FPGA_DELAY
#ccflags-y += -DFVL_SKIP_CHECK_ULD
#ccflags-y += -DREG_WRITE_PRINT
#ccflags-y += -DFVL_NO_NVM_AUTOLOAD
#ccflags-y += -DFVL_FW_BYPASS
#ccflags-y += -DCHECK_LINK_BY_REG
#ccflags-y += -DIGNORE_LSE_EVENTS

#ccflags-y += -DI40E_VALIDATE_READ_CSR

#ccflags-y += -DI40E_ENDLESS_TX
ccflags-y += -DSV_SUPPORT
ccflags-y += -DI40IW
ccflags-y += -DSYSLOG_PRINTS
#ccflags-y += -DI40IW_DEBUG_WQE
#ccflags-y += -DRS_BIT_NO_OVERWRITE
#ccflags-y += -DIW_PRINT_FW_DEBUG_PROBE
#ccflags-y += -Winline
#ccflags-y += -DCHECKER_DISABLED
#ccflags-y += -DI40E_FPK_FPGA_5
#ccflags-y += -DI40E_IGNORE_BLANK_NVM
#ccflags-y += -DI40E_IGNORE_RESET_COMPLETION_TIMEOUT
#ccflags-y += -DDISABLE_VECTOR_0_AFFINITY

#ccflags-y += -DRECOVER_MISSING_GRST
#ccflags-y += -DBH_IRQ

# these flags are mutualy exclusive
#ccflags-y += -DVELOCE
#ccflags-y += -DFPK_ESS


#ccflags-y += -DSKIP_PFR

ccflags-y += -Wno-format
ccflags-y += -Wno-unused-variable
ccflags-y +=	-Wunused-label


######## debug flags ####################
#ccflags-y += -DTX_DBG
#ccflags-y += -DWRITE_REG_DUMP
#ccflags-y += -DPRINT_TX_BUFFER
#ccflags-y += -DFVL_A0_BU_FOR_FW
#ccflags-y += -DI40E_AQ_PRINT_BUFFER

ccflags-y += -DAQ_CMD_CLEAR_PXE
######## workarounds flags ####################
#ccflags-y += -DTRIGGER_SW_INTR_WA
#ccflags-y += -DCALL_TX_HANDLER_ON_HANG
#ccflags-y += -DFW_TIMEOUT_RECOVERY

  
ifneq ($(REDHAT_DISTRIB),)
	ccflags-y += -DNO_CUSTOM_KMEM_CACHE
endif


# If we compile for SVOS, change target module name (suffix it with "sv")
ifeq ($(SVOS),1)
	ccflags-y += -DSVOS
	TARGET_OBJ = i40esv.o
	OBJECTS = i40esv-y
else
	TARGET_OBJ = i40e.o
	OBJECTS = i40e-y
endif

obj-m += $(TARGET_OBJ)


$(OBJECTS):=   shared/i40e_common.o\
        shared/i40e_adminq.o\
		shared/i40e_hmc.o\
		shared/i40e_lan_hmc.o\
                shared/i40e_nvm.o\
		shared/i40iw_hmc.o\
		shared/i40iw_ctrl.o\
		shared/i40iw_debug.o\
		shared/i40iw_uk.o\
		shared/i40iw_uda.o\
		shared/i40iw_uda_uk.o\
		shared/i40iw_virtchnl.o\
                shared/i40iw_vf.o\
		shared/iw40_pble.o\
		shared/kcompat.o\
		shared/i40iw_puda.o\
		shared/i40e_osdep.o\
		iwarp/i40iw_push.o \
		iwarp/iw_main.o\
		iwarp/iw_ctrl_cmds.o \
		iwarp/iw_pd.o \
		iwarp/iw_cq.o \
		iwarp/iw_qp.o \
		iwarp/i40iw_stag.o \
		iwarp/iw_cm.o \
		iwarp/i40iw_event_q.o \
		iw_shared/iw_resource_mgr.o\
		iw_shared/iw_stag.o \
		iw_shared/iw_aeq.o \
		iw_shared/iw_mmap.o \
		iw_shared/iw_shared_pbl.o\
		iwarp/iw_pbl.o \
        lan/i40e_main.o\
		lan/i40e_intr.o\
		lan/i40e_iov.o\
		lan/i40e_vmdq.o\
		lan/i40e_mem.o\
		lan/i40e_tx_ring.o\
		lan/i40e_rx_ring.o\
		lan/i40e_aq.o\
		lan/i40e_vsi.o\
		lan/i40e_fcoe.o\
		sv_shared/sv_main.o\
		sv_shared/sv_ctrl.o\
		sv_shared/sv_ctrl_cmds.o\
		sv_shared/sv_mem.o\
		sv_shared/sv_queue.o\
		sv_shared/sv_diag.o\
		sv_shared/sv_log.o\
		sv_shared/sv_error.o\
		sv_shared/sv_thx.o\
		sv_shared/sv_packetcollector.o\
		sv_shared/sv_intr.o\
		sv_shared/sv_iov.o\
		sv_shared/sv_fcoe.o\
		sv_shared/sv_exp_table.o\
		sv_shared/sv_events.o\
		sv_shared/sv_config.o\
		sv_shared/sv_rx_packet.o\
		sv_shared/sv_tx_ring.o\
		sv_shared/sv_rx_ring.o\
		sv_shared/sv_rx_ring_adv.o\
		sv_shared/sv_cc.o\
		sv_shared/sv_cc_desc_ops.o\
# it seem that we remove some critical operation from uda. need to restore from shared code.
#		shared/i40iw_uda.o\
#               shared/i40iw_uda_uk.o\
#Tzvika: looks like we do no use this code. after regressions i will totaly remove it.
#		shared/i40iw_pble.o\
#
#
.PHONY: print
print:
	@echo $(ccflags-y)
