################################################################################
#
#
# Copyright(c) 1999 - 2009 Intel Corporation. All rights reserved.
#
# Makefile for building igb sv driver
#
################################################################################
#ARCH := $(shell uname -m | sed 's/i.86/i386/')


ccflags-y += -I$(src)/../../sv_shared/
ccflags-y += -I$(src)/../inc/
ccflags-y += -I$(src)/../api/inc/
ccflags-y += -I$(src)/../../api/inc/

ccflags-y += -O2     # optimize for performance
ccflags-y += -Wno-unused-value

ccflags-y += -DSXP_TEST_MODE

obj-m += sxp_fpga.o

sxp_fpga-y := sxp.o \
		sxp_char.o
