################################################################################
#
# 
# Copyright(c) 2013 Intel Corporation. All rights reserved.
# 
# Makefile for building ixgbc canyon gamily sv driver
#
################################################################################
#ARCH := $(shell uname -m | sed 's/i.86/i386/')

REDHAT_DISTRIB:=$(shell grep -lr "Santiago" /etc/*-release 2>/dev/null)

ccflags-y += -I$(src)/../sv_shared/
ccflags-y += -I$(src)/../api/inc/
ccflags-y += -I$(src)/../ixgbc/ 
ccflags-y += -I$(src)/../ixgbc/shared/

ccflags-y += -O2     # optimize for performance
ccflags-y += -DIXGBC
ccflags-y += -DSYSLOG_PRINTS
ccflags-y += -DDMA_SW_FLUSH
ccflags-y += -DHW_SV
#ccflags-y += -Winline
#ccflags-y += -DCHECKER_DISABLED
ccflags-y += -DDESC_INVERT
#ccflags-y += -DNIANTIC_FPGA_SUPPORT 
ccflags-y += -DDRIVER_ONLY
#ccflags-y += -DMEMDEBUG
#ccflags-y += -DOLD_TX_HANDLER
#ccflags-y += -DSKIP_LOAD_ON_1_LANE
ccflags-y += -DDISABLE_FORCE_GEN3
#ccflags-y += -DTX_MOVE_TAIL_8_BY_8
ccflags-y += -DEXP_TABLE_NO_GAP

ccflags-y += -Wno-unused-variable

#ccflags-y += -DRRC_WW52

ifneq ($(REDHAT_DISTRIB),)
	ccflags-y += -DNO_CUSTOM_KMEM_CACHE
endif

######## debug flags ####################
#ccflags-y += -DTX_DBG
#ccflags-y += -DPRINT_CSR_WRITE
#ccflags-y += -DPRINT_PACKET_UID
#ccflags-y += -DDBG
#ccflags-y += -DPRINT_TX_BUFFER
  

obj-m += ixgbc.o

ixgbc-y :=   shared/fm10k_api.o \
                shared/fm10k_common.o \
                shared/fm10k_pf.o \
                shared/fm10k_vf.o \
		shared/fm10k_mbx.o \
		shared/fm10k_tlv.o \
		ixgbc_main.o \
		ixgbc_rx_ring.o \
		ixgbc_tx_ring.o \
		ixgbc_iov.o \
		ixgbc_intr.o \
		ixgbc_diag.o \
                sv_shared/sv_main.o\
                sv_shared/sv_ctrl.o\
		sv_shared/sv_rx_ring.o\
		sv_shared/sv_tx_ring.o\
		sv_shared/sv_rx_ring_adv.o\
		sv_shared/sv_ctrl_cmds.o\
                sv_shared/sv_mem.o\
		sv_shared/sv_diag.o\
                sv_shared/sv_queue.o\
                sv_shared/sv_log.o\
		sv_shared/sv_error.o\
                sv_shared/sv_packetcollector.o\
		sv_shared/sv_rx_packet.o\
                sv_shared/sv_intr.o\
                sv_shared/sv_exp_table.o\
                sv_shared/sv_events.o\
		sv_shared/sv_iov.o\
		sv_shared/sv_fcoe.o\
		sv_shared/sv_config.o\
                sv_shared/sv_thx.o
