#!/bin/bash

set -e

trap '{ (( $? != 0 )) &&  /bin/logger -s "$error" ;}' EXIT

regexmatch="nothing to commit"
home="/home/gitdummy"

cd "$home/kiev_FwKiev_team/"
error+=$(/usr/bin/git pull -q 2>&1)
cd - >/dev/null
[[ -d "$home/lan_sv-denver/teams/FwKiev_team/" ]] || mkdir "$home/lan_sv-denver/teams/FwKiev_team/"
/usr/bin/rsync -q -a --exclude=".git/" --delete --numeric-ids  "$home/kiev_FwKiev_team/" "$home/lan_sv-denver/teams/FwKiev_team/"

cd "$home/lan_sv-denver/"
/usr/bin/git checkout -q master
/usr/bin/git add -A .
if ! error1=$(/usr/bin/git commit -q -m 'automatic FwKiev_team sync' 2>&1); then
        error+=$error1
        if [[ ! $error1 =~ $regexmatch ]]; then
                exit 1
        fi
fi

error+=$(/usr/bin/git pull -q --rebase 2>&1)
error+=$(/usr/bin/git push -q  origin master 2>&1)
