#!/bin/bash

declare -A description
[[ ! $gerrituser ]] && exit 1

case $@ in
	*get)
		while IFS=\= read -r variable value; do
			description[$variable]=$value
		done
		description[username]=$gerrituser

		num=${#description[@]}
		for key in "${!description[@]}"; do
			printf "%s\n" "$key=${description[$key]}"
			(( ++i == num )) && echo
		done | /usr/libexec/git-core/git-credential-cache "$@"
		exit $?
		;;
	*store)
		cat | /usr/libexec/git-core/git-credential-cache "$@"
		exit $?
		;;
	*erase)
		cat | /usr/libexec/git-core/git-credential-cache "$@"
		exit $?
		;;
esac
exit 0
