#!/bin/bash

socket="/var/run/git_post_receive/socket.file"
trap 'kill $COPROC_PID >/dev/null 2>&1' EXIT

coproc AUTOSSH_GATETIME=0 autossh -M0 -- -o PasswordAuthentication=no sshtunnel@lab-git "killall nc 2>/dev/null >&2 ;rm -f \"$socket\" 2>/dev/null 1>&2;exec nc -l -k -n -U \"$socket\""

sleep 3
kill -0 "$COPROC_PID" 2>/dev/null || exit 1

while read -r -a repos -u ${COPROC[0]}; do
        /usr/local/bin/push_denver "${repos[@]}" >&${COPROC[1]} || exit 1
        echo TERMINATE >&${COPROC[1]} || exit 1
done

exit 0
