#!/bin/bash

##1'st parameter = family name
##2'nd parameter = product name
##3'rd parameter = adapter name
###########################################
##################################################################################

##################################################################################
###########################################


function PrintHelp {
	echo "usage is:"
	echo " 		-t TeamName -f FamilyName "
}

TNameExists=0
FNameExists=0
PNameExists=0
while getopts ":t:f:h" optname
  do
    case "$optname" in
      "t")
	TNameExists=1
	TName="$OPTARG"
        ;;
      "f")
	FNameExists=1
	FName="$OPTARG"
        ;;
      "h")
	PrintHelp
	exit -1
	;;
      "?")
        echo "Unknown option $OPTARG"
	PrintHelp
	exit -1
        ;;
      ":")
        echo "No argument value for option $OPTARG"
	PrintHelp
	exit -1
        ;;
      *)
      # Should not occur
        echo "Unknown error while processing options"
        ;;
    esac
  done

if [ "$FNameExists" -ne 1 ]
then
	echo "option -f missing, -h for help"
	exit -1
fi
if [ "$TNameExists" -ne 1 ]
then
	echo "option -t missing, -h for help"
	exit -1
fi




##########infrastructure##################

rm -rf `find ../TemplateTeam/ -name CVS`

cd infrastructure/family/inc/
cp ../../../../TemplateTeam/infrastructure/family/inc/CFamilyNAMETest.h "C${FName}Test.h"
cd ../src/
cp ../../../../TemplateTeam/infrastructure/family/src/CFamilyNAMETest.cpp "C${FName}Test.cpp"

cd ../

sed -i "s/FamilyNAME/${FName}/g" "src/C${FName}Test.cpp"
sed -i "s/FamilyNAME/${FName}/g" "inc/C${FName}Test.h"
cd ../../

##looks like we are done with infrastructure
##########################################
##first ,family

cd tests/
cd family/
mkdir "${FName}"
cd "${FName}"
cp -r ../../../../TemplateTeam/tests/family/TemplateFamilyNAME/* ./


mv src/CFirstFamilyTest.cpp "src/C${FName}FirstTest.cpp"
mv inc/CFirstFamilyTest.h "inc/C${FName}FirstTest.h"

sed -i "s/FamilyNAME/${FName}/g" "inc/C${FName}FirstTest.h"
sed -i "s/FamilyNAME/${FName}/g" "src/C${FName}FirstTest.cpp"

sed -i "s/CFirstFamilyTest/C${FName}FirstTest/g" "inc/C${FName}FirstTest.h"
sed -i "s/CFirstFamilyTest/C${FName}FirstTest/g" "src/C${FName}FirstTest.cpp"

sed -i "s/FAMILY_ADAPTERS_INCLUDE/$FName/g" src/Makefile
sed -i "s/FAMILY_ADAPTERS_INCLUDE/$FName/g" Makefile

cd ../../../

for makefile in $(find ./ -name "Makefile");
do
	sed -i "s/TemplateTeamNAME/${TName}/g" $makefile
	cp ../../GNUmakefile "${makefile%/*}"
done
##########################################################
##########Add Adapters Lib to team########



CurrentAdapters=`grep -w "ADAPTERS :="  my_team.mk`
NewAdapters=" ${CurrentAdapters} ${FName} "
sed -i "s/${CurrentAdapters}/${NewAdapters}/g" "my_team.mk"
#goodCurrentAdapter=`echo "$CurrentAdapters"|sed 's?/?\\\/?g'`





