################################################################################
# 
# Copyright(c) 1999 - 2010 Intel Corporation. All rights reserved.
# 
# Makefile for building cpm driver
#

#
################################################################################
#ARCH := $(shell uname -m | sed 's/i.86/i386/')

#ccflags-y += -I$(src)ared/
ccflags-y += -I$(src)/../api/inc
ccflags-y += -I$(src)/../../api/inc

ccflags-y += -DCPM
ccflags-y += -O2     # optimize for performance
#ccflags-y += -Winline

######## driver flags ####################
#ccflags-y += -DCPM_INTERRUPTS
  
obj-m += cpm.o

cpm-y := 	cpm_char_ctrl.o \
		cpm_ctrl_cmd.o	\
		cpm_mem.o\
		cpm_main.o \
		cpm_ueng.o \
		cpm_sriov.o \
		cpm_intr.o
