################################################################################
#
# 
# Copyright(c) 1999 - 2009 Intel Corporation. All rights reserved.
# 
# Makefile for building e1000 sv driver
#
################################################################################
#ARCH := $(shell uname -m | sed 's/i.86/i386/')

REDHAT_DISTRIB:=$(shell grep -lr "Santiago" /etc/*-release 2>/dev/null)

ccflags-y += -I$(src)/../sv_shared/
ccflags-y += -I$(src)/../api/inc/
ccflags-y += -I$(src)/../e1000/
ccflags-y += -I$(src)/./shared/

ccflags-y += -O2     # optimize for performance
ccflags-y += -DE1000
ccflags-y += -DHW_SV
ccflags-y += -DSYSLOG_PRINTS
ccflags-y += -DDMA_SW_FLUSH
#ccflags-y += -Winline
ccflags-y += -Wno-unused-value
ccflags-y += -Wno-unused-variable
#ccflags-y += -DCHECKER_DISABLED
#ccflags-y += -DTX_DBG
#ccflags-y += -DDBG  
ccflags-y += -DEXP_TABLE_NO_GAP
  
ifneq ($(REDHAT_DISTRIB),)
	ccflags-y += -DNO_CUSTOM_KMEM_CACHE
endif


# If we compile for SVOS, change target module name (suffix it with "sv")
ifeq ($(SVOS),1)
	TARGET_OBJ = e1000esv.o
	OBJECTS = e1000esv-y
else
	TARGET_OBJ = e1000e.o
	OBJECTS = e1000e-y
endif

obj-m += $(TARGET_OBJ)

$(OBJECTS) :=	shared/e1000_82571.o\
		shared/e1000_mac.o \
		shared/e1000_ich8lan.o \
		shared/e1000_80003es2lan.o\
		shared/e1000_nvm.o \
		shared/e1000_phy.o \
		shared/e1000_manage.o \
		shared/kcompat.o \
		e1000_main.o\
		e1000_rx_ring.o \
		e1000_tx_ring.o \
		e1000_mem.o \
		e1000_intr.o \
		e1000_diag.o\
                sv_shared/sv_main.o\
                sv_shared/sv_ctrl.o\
		sv_shared/sv_ctrl_cmds.o\
                sv_shared/sv_mem.o\
		sv_shared/sv_rx_ring.o\
		sv_shared/sv_rx_isr.o\
		sv_shared/sv_tx_ring.o\
		sv_shared/sv_diag.o\
                sv_shared/sv_queue.o\
                sv_shared/sv_log.o\
		sv_shared/sv_error.o\
                sv_shared/sv_packetcollector.o\
		sv_shared/sv_rx_packet.o\
                sv_shared/sv_intr.o\
                sv_shared/sv_exp_table.o\
                sv_shared/sv_events.o\
		sv_shared/sv_config.o\
                sv_shared/sv_thx.o\
		sv_shared/sv_cc.o\
		sv_shared/sv_cc_desc_ops.o\
