ADAPTER_NAME := FCs/Generic
skip_dirs := infrastructure
NAME := GenericFCsFamily
LIBS = $(FC_DEP_IPS_ADAPTERS_FINAL_LIBS)

define message
@echo "FC_DEP_IPS_ADAPTERS $(FC_DEP_IPS_ADAPTERS)"
@echo "FC_DEP_ALL_IPS_FULL_PATH" $(FC_DEP_ALL_IPS_FULL_PATH)
@echo "FC_DEP_IPS_ADAPTERS_FINAL_LIBS" $(FC_DEP_IPS_ADAPTERS_FINAL_LIBS)
@echo "FC_DEP_IPS_ADAPTERS_FINAL_INC" $(FC_DEP_IPS_ADAPTERS_FINAL_INC)
@echo "FC_DEP_IPS_ADAPTES_NAME_FOR_LINKING" $(FC_DEP_IPS_ADAPTES_NAME_FOR_LINKING)
#@echo "FC_DEP_ALL_IPS_FULL_PATH : "$(FC_DEP_ALL_IPS_FULL_PATH)
#@echo "FC_DEP_ALL_IPS_FULL_PATH : " $(FC_DEP_ALL_IPS_FULL_PATH) >> /home/lassor-l/development/Denver/adapters/FCs/Generic/k
#@echo "ip: " $@ >> /home/lassor-l/development/Denver/adapters/FCs/Generic/k
endef

include ../../includes/lib.mk


