#!/bin/bash



function PrintHelp {
	echo "usage is:"
	echo " 		-f FamilyName -p ProductName"
}


FNameExists=0
PNameExists=0
while getopts ":f:p:h" optname
  do
    case "$optname" in
      "f")
	FNameExists=1
	FName="$OPTARG"
        ;;
      "p")
	PNameExists=1
	PName="$OPTARG"
        ;;
      "h")
	PrintHelp
	exit -1
	;;
      "?")
        echo "Unknown option $OPTARG"
	PrintHelp
	exit -1
        ;;
      ":")
        echo "No argument value for option $OPTARG"
	PrintHelp
	exit -1
        ;;
      *)
      # Should not occur
        echo "Unknown error while processing options"
        ;;
    esac
  done

if [ "$FNameExists" -ne 1 ]
then
	echo "option -f missing, -h for help"
	exit -1
fi
if [ "$PNameExists" -ne 1 ]
then
	echo "option -p missing, -h for help"
	exit -1
fi





###
### 1'st parameter is path
function ChangeProductFiles {
	cd "$1"
	for old_file in CPRODUCTNAME*;
	do
		no_prefix="${old_file##CPRODUCTNAME}"
		new_prefix=C$PName$no_prefix
		mv "$old_file" "$new_prefix" 
		#echo "$new_prefix"
	done
}


### 1'st parameter is path
function ChangeFamilyFiles {	
	cd "$1"
	for old_file in CFAMILYNAME*;
	do
		no_prefix="${old_file##CFAMILYNAME}"
		new_prefix=C$FName$no_prefix
		mv "$old_file" "$new_prefix" 
		#echo "$new_prefix"
	done
}

#######make new family###########

mkdir "$FName"
cp -rf TemplateAdapter/* "$FName"/
cd "$FName"

#######change file name in infrastructure####

ChangeProductFiles infrastructure/inc
cd ../../
ChangeFamilyFiles infrastructure/inc
cd ../../
ChangeProductFiles infrastructure/src
cd ../../
ChangeFamilyFiles infrastructure/src
cd ../../
##################change adapterClasses##########################
ChangeFamilyFiles AdapterClasses/family/src
cd ../../../
ChangeFamilyFiles AdapterClasses/family/inc
cd ../../../
ChangeProductFiles AdapterClasses/products/inc
cd ../../../
ChangeProductFiles AdapterClasses/products/src
cd ../../../
#################change files inisde###########################


for file in $(find ./infrastructure);
do
	if [ -f $file ]
	then
		sed -i "s/FAMILYNAME/$FName/g" $file
		sed -i "s/PRODUCTNAME/$PName/g" $file
	fi
done

for file in $(find ./AdapterClasses);
do
	if [ -f $file ]
	then
		sed -i "s/FAMILYNAME/$FName/g" $file
		sed -i "s/PRODUCTNAME/$PName/g" $file
	fi
done

for file in $(find ./ -name Makefile);
do
	if [ -f $file ]
	then
		sed -i "s/FAMILY_NAME/$FName/g" $file
		cp ../../../GNUmakefile "${file%/*}"
	fi
done


rm -rf `find ./ -name CVS`





