################################################################################
# 
# Copyright(c) 1999 - 2010 Intel Corporation. All rights reserved.
# 
# Makefile for building ne020 iwarp dv driver
#

#
################################################################################
#ARCH := $(shell uname -m | sed 's/i.86/i386/')

ccflags-y += -I$(src)/./
ccflags-y += -I$(src)/../api/inc/
ccflags-y += -I$(src)/../iw_shared/
ccflags-y += -I$(src)/../api/iwarp/inc/
ccflags-y += -I$(src)/shared/
ccflags-y += -I$(src)/../sv_shared/

ccflags-y += -DNES
ccflags-y += -DIWNES
#ccflags-y += -DDEBUG_REF_COUNT
ccflags-y += -O2     # optimize for performance
#ccflags-y += DSYSLOG_PRINTS
ccflags-y += -DSINGLE_PORT
ccflags-y += -DSV_DRIVER
#ccflags-y += -Winline
ccflags-y += $(call cc-disable-warning, format)
ccflags-y += $(call cc-disable-warning, unused-variable)
ccflags-y += $(call cc-disable-warning, unused-function)

######## debug flags####################
#ccflags-y += -DWRITE_REG_DUMP
  

# If we compile for SVOS, change target module name (suffix it with "sv")
ifeq ($(SVOS),1)
	ccflags-y += -DSVOS
	TARGET_OBJ = iwnessv.o
	OBJECTS = iwnessv-y
else
	TARGET_OBJ = iwnes.o
	OBJECTS = iwnes-y
endif

obj-m += $(TARGET_OBJ)

$(OBJECTS):=    nes.o \
		nes_hw.o \
		nes_nic.o \
		nes_utils.o \
		nes_cm.o \
		iw_pd.o \
		iw_cq.o \
		iw_qp.o \
		nes_stag.o \
		iw_main.o \
		nes_event_q.o \
		../iw_shared/iw_resource_mgr.o \
		../iw_shared/iw_stag.o \
		../iw_shared/iw_aeq.o \
		../iw_shared/iw_mmap.o \
		../iw_shared/iw_shared_pbl.o\
		iw_pbl.o \
		../sv_shared/sv_mem.o \
		iw_char_ctrl.o \
		iw_ctrl_gen.o \
		iw_ctrl_iwarp.o \
		shared/ne020_iwarp.o \
		shared/ne020_iwarp_u_k.o \
		shared/ne020_nic_qp.o \
		\
		\
		../sv_shared/sv_queue.o \
		../sv_shared/sv_events.o \
