.PHONY: all src
default: src
all: src

src:		
	@printf "\n%s\n" "********************* build $(CURDIR) **************************"
	$(MAKE) -C src

clean:
	$(MAKE) -C src clean

include ../../misc.mk
